### ISSUE TITLE
400 Bad Request: DHL-Auth Token not set

### ISSUE THREAD

**Issue by AdnanSarwarMe** [Nogrod/dhl-retoure-php-sdk#1]
Hi,
 I tried to call API for Return Labels. 
As per test file, On username I provided my AppID:
On Password: I provided my App Token.

The exact error is: 
`Exception when calling ReturnsApi->rootPost: [400] Client error: "POST https://cig.dhl.de/services/production/rest/returns/" resulted in a "400 Bad Request" response: {"code":400,"detail":"DHL-Auth Token not set"}`

My config variable looks like this.

`$config = Dhl\Rest\Retoure\Configuration::getDefaultConfiguration()->setApiKey('MjIyMjIyMjIyMl9jdX********QlFiWjYyIVppQmlWVmJoYw==', 'Repartus_2');`

Repartus_2 is my App ID from Entwickler portal. And hide few characters for DHL-Auth Token for security reasons.

What I'm doing wrong. I know the issue is with config variable. But I set the DHL Auth token, what to put on second parameter and where to get it?

Thanks for your time, I need urgent solution for it please. I'll appreciate it.

**Comment by Nogrod** [comment]
hey, i use the config the following way:
```
Configuration::getDefaultConfiguration()
            ->setUsername('api_user')
            ->setPassword('api_pass')
            ->setApiKey('DPDHL-User-Authentication-Token', base64_encode('user'.':'.'pass'));
```
api_user & api_pass should be your app id and app token
user & pass should be your dhl dev user and pass

**Comment by AdnanSarwarMe** [comment]
Thanks so much mate. Looks like it is authenticated properly now.

But I get this error now. What could be the issue? 

`Exception when calling ReturnsApi->rootPost: [500] Server error: "POST https://cig.dhl.de/services/production/rest/returns/" resulted in a "500 Server Error" response: {"statusCode":"500","statusText": "Server Error"}`

The below is my full file code:

`<?php
require_once(__DIR__ . '/vendor/autoload.php');
// Configure HTTP basic authorization: appAuth

$config = Dhl\Rest\Retoure\Configuration::getDefaultConfiguration()
              ->setUsername('xxx')
              ->setPassword('xxx')
              ->setApiKey('DPDHL-User-Authentication-Token', base64_encode('xxx'.':'.'xxx'));



$apiInstance = new Dhl\Rest\Retoure\Api\ReturnsApi(
    // If you want use custom http client, pass your client which implements `GuzzleHttp\ClientInterface`.
    // This is optional, `GuzzleHttp\Client` will be used as default.
    new GuzzleHttp\Client(),
    $config
);
$return_order = new \Dhl\Rest\Retoure\Model\ReturnOrder(); // \Dhl\Rest\Retoure\Model\ReturnOrder | The object contains the details of the sender, the returnshipment and references.

try {
    $result = $apiInstance->rootPost($return_order);
    print_r($result);
} catch (Exception $e) {
    echo 'Exception when calling ReturnsApi->rootPost: ', $e->getMessage(), PHP_EOL;
}

?>`

**Comment by Nogrod** [comment]
you need to set the fields receiverId and senderAdress of ReturnOrder since they are required fields

**Comment by AdnanSarwarMe** [comment]
> you need to set the fields receiverId and senderAdress of ReturnOrder since they are required fields

I'm sorry for this silly questions. How do I do that? Can you please specify steps? I'll really appreciate it mate.

**Comment by Nogrod** [comment]
here is an example with most common fields
```
$return_order->setReceiverId('receiverId'); // dhl gk portal -> retoure -> settings
$return_order->setEmail('mail@example.com');
$return_order->setTelephoneNumber('+49123456789');
$sender = new SimpleAddress();
$sender->setName1('name');
$sender->setName2('name2');
$sender->setName3('name3');
$sender->setStreetName('street');
$sender->setHouseNumber('houseNumber');
$sender->setPostCode('zip');
$sender->setCity('city');
$country = new Country();
$country->setCountryIsoCode('iso-alpha-3-code');
$sender->setCountry($country);
$return_order->setSenderAddress($sender);
$return_order->setCustomerReference('ref');
$return_order->setShipmentReference('ref');
$return_order->setReturnDocumentType('BOTH'); //SHIPMENT_LABEL, QR_LABEL or BOTH
```

**Comment by AdnanSarwarMe** [comment]
I think I'm almost there.

Now in DPDHL, I put my Entwickler Developer ID & Pass for Test and it says:
`Authentification failed: User not found or password invalid`

I put username & password as per my DHL Germany Business Portal. It says:
`{"code":201,"detail":"Empfaenger ist nicht verfuegbar."}`

Means "Recipient is not available.". What I'm doing wrong now? I think I'm almost to the finishing.

**Comment by Nogrod** [comment]
sandbox and production have different credentials and also receiverId, you can find the info here:
[https://entwickler.dhl.de/group/ep/wsapis/retouren/authentifizierung](https://entwickler.dhl.de/group/ep/wsapis/retouren/authentifizierung)

**Comment by AdnanSarwarMe** [comment]
Nevermind. I got it to solved. It was receiverId issue.

Now it works and shows me the [shipment_number] etc.

I wanted something that as soon as API hits, it goes to DHL web where user can generate there label/qr code.

Anyways. Everything is working as expected. Thanks, mate!

**Comment by AdnanSarwarMe** [comment]
Like for example, I want to create this type of link to send user here: 

`https://www.dhl.de/retoure/gw/rpcustomerweb/OrderEntry.action?hash=81f418de085b755dxxxxxxxx04da6a859585b64f13a9d58363cd31b695e791c&ADDR_SEND_EMAIL=adnansarwar0123%40gmail.com&ADDR_SEND_FIRST_NAME=adnan%20sarwar&ADDR_SEND_STREET=Gurlittstra%C3%9Fe%2018&ADDR_SEND_ZIP=40223&ADDR_SEND_CITY=D%C3%BCsseldorf&ADDR_SEND_STREET_ADD=RP16431`

How do I do this? It also requires hash.

**Comment by Nogrod** [comment]
You can have a DHL Retoure Customer Portal for that, just ask DHL about it.

The API returns you the requested pdf file (SHIPMENT_LABEL, QR_LABEL or BOTH)
`file_put_contents($tmpFile, base64_decode($result->getLabelData())); `

**Comment by AdnanSarwarMe** [comment]
Thank you so much mate. I really appreciate the help you did and put your time here. 
Thanks a lot. Everything is working as expected and working as required. Thanks..
